### ISSUE TITLE
Update JS Client to use Token Manager

### ISSUE THREAD

**Issue by brockallen** [IdentityServer/Thinktecture.IdentityServer3.Samples#52]
The JS client is messy right now -- needs an update.

**Comment by leastprivilege** [comment]
we still need a simple JS client without all the bells & whistles.

Initiate request, validate callback - extract token

**Comment by brockallen** [comment]
Just an oauth2 sample, you mean?

**Comment by leastprivilege** [comment]
yes

From:  Brock Allen
Reply-To:  "IdentityServer/Thinktecture.IdentityServer3.Samples"
Date:  Mittwoch, 28. Januar 2015 02:18
To:  "IdentityServer/Thinktecture.IdentityServer3.Samples"
Cc:  Dominick Baier
Subject:  Re: [Thinktecture.IdentityServer3.Samples] Update JS Client to 
use Token Manager (#52)


Just an oauth2 sample, you mean?

**Comment by leastprivilege** [comment]
wanna merge to master?
