### ISSUE TITLE
Should Webhost (minimal) example enable RAMMFAR

### ISSUE THREAD

**Issue by herskinduk** [IdentityServer/Thinktecture.IdentityServer3.Samples#59]
I deployed the Webhost (minimal) in Azure WebSites and had a world of pain because I forgot to enable RAMMFAR. Should RAMMFAR be enabled by default for this example or is this just down to me using Azure?

**Comment by leastprivilege** [comment]
oh - did i forget that? that's a bug. thanks!

**Comment by leastprivilege** [comment]
updated on dev - will be merged to master for RTM
