### ISSUE TITLE
Sample for PreAuthenticate

### ISSUE THREAD

**Issue by leastprivilege** [IdentityServer/Thinktecture.IdentityServer3.Samples#61]

**Comment by brockallen** [comment]
From https://github.com/thinktecture/Thinktecture.IdentityServer.v3/issues/483

**Comment by giulianob** [comment]
Hey is this sample available somewhere now? I couldn't find it and was really curious how to implement auto login with PreAuthenticate.

**Comment by brockallen** [comment]
on dev. the same doesn't do the auto login -- it uses PreAuthN to do HRD.

**Comment by sania13** [comment]
Anyone found sample how to use PreAuthenticate? 

What does that mean "PreAuthN to do HRD" ?

**Comment by brockallen** [comment]
There are lots of samples in the samples repo. In fact, there's one for PreAuthenticate (under the CustomHrd folder).

**Comment by sania13** [comment]
Thank you Brock. 
I am trying to get Current User Name from WindowsPrincipal, but not successful. ('Windows Authentication' is Enabled and 'Anonymous Authentication' is Disable. I will host the app on IIS.

Any suggestions?
