### ISSUE TITLE
I want to customise the views in the AspnetIdentity sample

### ISSUE THREAD

**Issue by laitang2000** [IdentityServer/Thinktecture.IdentityServer3.Samples#68]
Hi I would like to customise the views in the AspnetIdentity sample. I can't see how to do this in the solution. Any pointers?

Thanks

**Comment by brockallen** [comment]
Customizing views is covered in the docs.

**Comment by laitang2000** [comment]
Ah I've been the doc so many times! And until you insisted it was there I didnt do a ctl+f!
Many thanks and keep up the good work!
