### ISSUE TITLE
Identity Server tutorial - Identity Server First Steps - getting started 

### ISSUE THREAD

**Issue by OscarAgreda** [IdentityServer/Thinktecture.IdentityServer3.Samples#69]
IdentityServer3 is just outstanding , not only is the best and only one in this category , but is just awesome to see the elegance on the code and super human security code practices.

i have some issues /questions  
1-the samples do not get the latest versions on the Thinktecture packages , it seems as if the samples reference older version that do not exist therefore some samples do not work

2- have been searching everywhere for a good tutorial on MembershipReboot support, something like the MVC walk-through you have on the documentation . 

3-I got the MembershipReboot sample to run with these packages http://grab.by/EeVc but if i try to login http://grab.by/EeW6 always get the exception http://grab.by/EeWc

this project is great, thanks for educating the world on security ,

Thank you for you hard work

**Comment by brockallen** [comment]
Thanks for the kind words.

1) The samples (on master) should be referencing from MyGet, which should be the same code that is released on NuGet. We did it that way because it's a tremendous hassle to update each sample to point to the same build on NuGet that we have on MyGet.

2) We don't have a MR tutorial, just the sample in the samples repo. MR is (slightly) documented on the MR repo wiki on github.

3) The exception dialog doesn't really help. Did you enable logging to see the actual errors?

**Comment by OscarAgreda** [comment]
Thanks
is such an "out of the box error" that i created this 2 minutes video for you http://goo.gl/FcXXoT of what happens every time i want to authenticate by google.   how could i manage to add users by the way .

Once i get all this figured out, is it OK if i make a video for the community on how to get it up and running from zero to full Membership Reboot resource Authorization server fully operational .

**Comment by OscarAgreda** [comment]
And for anyone arriving here from a search engine.

I will suggest to start here 
1-http://chimera.labs.oreilly.com/books/1234000001708/ch16.html#_client_applications

then go here
2-http://identityserver.github.io/Documentation/docs/overview/terminology.html

listen to this podcast
3-http://www.dotnetrocks.com/default.aspx?showNum=1089

at this point, you will be thinking how come this amazing code is open source.. And if you are like me, i was doing all of this by myself, and realized in 3 weeks i have only accomplished 5% of what Identity Server can do; so it would have taken me almost a year to do all this, plus the code will  probably not be so elegant and simple plus Dominick  and Brock Allen are such experts on the matter that is crucial for a good software architecture.

at last, do this tutorial 
4-http://identityserver.github.io/Documentation/docs/overview/mvcGettingStarted.html

**Comment by brockallen** [comment]
So did you get it all sorted out now?

**Comment by OscarAgreda** [comment]
I was able to learn/run the MembershipReboot inside Thinktecture.IdentityServer3.Samples
http://grab.by/Ehhg

How do I grant application permissions  to access some methods inside Web Api controllers 

Regards

**Comment by brockallen** [comment]
The user service is what interacts with your identity management library. We have one for MembershipReboot and another one for AspNet Identity. Those are two different implementations.

**Comment by OscarAgreda** [comment]
where could I read more about all of this ? any blog, article, sample code, pluralsight video or book ?

**Comment by brockallen** [comment]
The docs: http://identityserver.github.io/Documentation/

**Comment by OscarAgreda** [comment]
i have  spend my week on those docs
the typical user case nowdays will be to have identity serer 3 managing authentication using a couple of providers like aspNetIdentity and Google, then using the power of Identity Server to to manage users , plus having membership reboot to be able to do a lot more , like multi-tenant for example all of this to Authorize some webapi resources.
I think is a very cummun scneaio for most users

**Comment by brockallen** [comment]
If the user service docs don't help, then (as of right now) the other thing I can suggest is to read the source code for the AspNet Identity user service.

**Comment by OscarAgreda** [comment]
what about the following steps
1-create a new webapi app
2-use nuget to install IdentityServer3
3-continue by adding the MembershipReboot and AspIdentity plug ins for indentityserver3
4 - setup the connectionStrings 
all of the above makes sense and it can be learned from the samples and documentations

now ..  do i need any other package http://grab.by/Ekcq

can you just please help with the StartUp.cs  to put it all together

-user coming from the aspNetIdentity database (configured on web.config)
-managed by MembershipReboot ( just what MembershipReboot was intended for) 
-Identity Server being the "Cop directing traffic"
-Thinktecture.IdentityModel.Owin.ResourceAuthorization helping to restcit access to some Web API

this is the closest, i think
https://github.com/brockallen/BrockAllen.MembershipReboot/blob/master/samples/WebApiResourceOwner/ServerApp/Startup.cs

Everything I need to add and configure is to the Startup.cs, right 
Can you provide a sample of that ?

That will be of tremendous help to put it all together 

you have to understand that having so many packages and plugins and thing that can be added (different namespaces) is incredible confusing ..

i have been very close , but not knowing hot to configure the startup.cs always takes me down.  
see this is about security, i know that if I do it wrong  i am putting all of my software at risk ..

Please just help with the startup.cs

**Comment by brockallen** [comment]
I'm not sure why you want both MembershipReboot and AspNetIdentity -- they do the same thing.

We already have many samples and a walk though and we try to document the NuGets and what they are for. Perhaps you need consulting then if what's already been provided isn't sufficient.

**Comment by OscarAgreda** [comment]
oh i see . it's one of those Open Sources  with that Business Model that are very different with the new  google developers angularJS type of Open Sources.
Thanks for your time and sorry for the inconveniences.

**Comment by leastprivilege** [comment]
Not sure I understand that comment - you care to explain?

**Comment by OscarAgreda** [comment]
one of such open source project is breeze.js from ideablade , in which they do good and very useful javacript library. (breeze.js created lots and lots of tutorials , documentation and people like John Papa helped them in their marketing campaign) . but when many enterprise starting to adopt breeze.js . the question arose on how does IdeaBlade is going to make money . they have developers that had invested their time and they obviously need to needed to feed their families .so people and the Enterprise started to worry that if adopted what will happen 3 years down the road , if the project was going to be sustainable , etc..  see when a library is for the Enterprise , as i am sure you know, there are many consideration that need to be made before adopting it...   so breeze.js that is in the past, because now they have a subscription based licence http://www.getbreezenow.com/support that is very easy for all of us just to purchase . that we know the company is going to be with us 3 years from now. nowdays in BreezeJs , the "Team support package" has become very popular . because most developer just tell their companies. "Hey, we need this to makes us 5 times faster when working with data" and the company just purchase it.
in the case of AngularJs, they have incredible brain power behind their products (just like IndentyServer) . but angular does not need to sell  a subscription, Google makes millions out of their advertisement .
so 2 different types of openSource business Models

**Comment by leastprivilege** [comment]
I still can't make the connection here - Brock was just telling you that if documentation and samples are not enough - you might need some consulting for the basics. Not necessarily from us.

We are indeed a small team and try to help wherever we can - but we also have a "day job".

**Comment by OscarAgreda** [comment]
yes, i understand, but i am not saying for the help, as if i expect free consulting services.. i am saying that the documentation is obviously confusing on the fact that there are so many nuget packages , and i mean a loot of possibilities based on just the name of the package.

so you are saying that I will be bale to use indentity server 3 (fully and the the way it was created for) just by reading the sample and the documentation ?  because if that is the case, then i have not done my homework.

**Comment by leastprivilege** [comment]
Yes that's what I am saying - play around with it and feel free to open issues when you have more specific questions.

**Comment by OscarAgreda** [comment]
ok. sounds good. 
sorry for the confusion .

**Comment by OscarAgreda** [comment]
After many nights, lots of pain and frustration , a week ago i was able to get the whole stack working.
it is so awesome .
in case someone wants to start from zero to full, i have a recommendation 
-this is a great product, actually is simple the best, unfortunately when you are novice as i was 3 weeks ago, the documentation and samples will never get you anywhere and it is frustrating.
-But,, yes there is a "but" .. once you have done your homework and reviewed every single piece of code that makes up identity server 3 you will see how the documentation is perfect , is right to the point and very precise super awesome...
so the only way to get it all figured out is to endure the pain of confusion and conquer.
spend lots of time with the sample til you get it, you have to use them all to really learn.
this open source project is recommended by the Microsoft Patterns and Practices team https://msdn.microsoft.com/en-us/library/hh534483.aspx   http://xneterp.com/i/4W2g.png .
that is huuuuuge.
in the end I used the MembershipReboot + IdentityServer3 and pushed the identity server setting to azure using entity framework .

Now we have lots of Angular SPAs that use WebAPI and use Identity Server Bearer Token Authentication. Everything working in perfect synchronization. It is so awesome.

**Comment by OscarAgreda** [comment]
After feeling conformable with the Identity Server 3 code. I recommend these samples

1-https://github.com/brockallen/BrockAllen.MembershipReboot/tree/master/samples/SingleTenantOwinSystemWeb
2-https://github.com/IdentityServer/Thinktecture.IdentityServer3.MembershipReboot/tree/master/source
3-https://github.com/IdentityServer/Thinktecture.IdentityServer3.EntityFramework/tree/master/Source
4-https://github.com/IdentityServer/Thinktecture.IdentityServer3.Samples/tree/master/source/MVC%20Authentication

**Comment by achaffman** [comment]
Oscar, do you want to write up a walk through?  My problem is I'm still in webforms world, trying to understand the MVC code is not always straight forward.

**Comment by OscarAgreda** [comment]
Hello,
first things first.
you must get familiar with the samples
https://github.com/IdentityServer/IdentityServer3.Samples
Identity Server is not only for MVC as you will see on the many many different samples

**Comment by OscarAgreda** [comment]
@achaffman 
how is it going with your journey ?

**Comment by achaffman** [comment]
Honestly, I haven’t gotten anywhere with Identity Server.  I still feel like it’s not super clear for Webforms and I really don’t have the luxary of time to dissect the MVC code.  If you can share any code or advice, I would appreciate it.  A blog or something would go a long way!  Thanks for checking in though!

**Comment by brockallen** [comment]
It's not so much WebForms -- it's OWIN/Katana that you'd need to learn (given that you pretty much want to use the OpenID Connect middleware). And you will have to make time to learn a new programming model, because ASP.NET 5 is just more of this new way. Sorry to be the bearer of bad news.
