### ISSUE TITLE
TokenManager - processTokenCallbackSilent

### ISSUE THREAD

**Issue by israelpereira** [IdentityServer/Thinktecture.IdentityServer3.Samples#71]
Hi Guys ,

I'm using AngularJs and I was having an issue to use the "Silent Token Renew" .. TokenManager never find the id_token , because the return URL come with the hashtag # and the method " processTokenCallbackSilent " of the Token Manager  just get everything after the hashtag .. "# / frame / id_token = eyJ0eXAiOiJKV ... " ... so it makes impossible the other methods find the id_token ..

My Solution was change the method " processTokenCallbackAsync" .. putting a parameter to directly receive the response of the idsrv.

```javascript
// This part is where you call the Callback Silent
// send just the "id_token = eyJ0eXAiOiJKV... "
idmTokenManager.processTokenCallbackSilent ( $ stateParams.response );
```

```javascript
TokenManager.prototype.processTokenCallbackSilent = function (queryString) {
    if (window.top && window !== window.top) {
        if (queryString) {
            window.top.postMessage(queryString, location.protocol + "//" + location.host);
        }
    }
}
```

IdentityServer/Thinktecture.IdentityServer3#751
This was a similiar problem, already solved, doing the same as identity manager does.

Hope it helps..

Thanks.

**Comment by brockallen** [comment]
Ok, added to dev branch.

**Comment by israelpereira** [comment]
The change was made on oidc.js file.. but it is the output of the oidc.js.bundle

I think it was a mistake, wasn't it?

IdentityServer/Thinktecture.IdentityServer3.Samples@8c529829f9fcca926b7a2881bf8ab538f5e755d1

Thanks

**Comment by brockallen** [comment]
Yep, good catch. thanks. fixed on dev (again).
