### ISSUE TITLE
I am getting certificate error in OAuth Client Flow

### ISSUE THREAD

**Issue by skatukojwala** [IdentityServer/Thinktecture.IdentityServer3.Samples#76]
We are using code flow with our application

All of the sudden I am getting certificate error with 
OAuth2Client::RequestAuthorizationCodeAsync( 
code, callbackURL); 

Which certificate is this using?.  Is it using IE Certificate 'or' do we need to setup some certificate for this.

**Comment by leastprivilege** [comment]
It's SSL - SSL must be setup correctly.

**Comment by skatukojwala** [comment]
Thank you for quick response.  On the same machine your clients samples work without any problem, but our application was failing.  I will look into this SSL setup next week.

**Comment by bcbeatty** [comment]
I'm running on the localhost, But I'm getting this error also. Do you have insights on what could be wrong with SSL ?

    var tokenClient = new OAuth2Client(
        new Uri(IdConstants.TokenEndpoint),
	IdConstants.ClientId,
	"secret");

	var response = await tokenClient.RequestAuthorizationCodeAsync(n.Code, n.RedirectUri);
	if (response.IsError)//always returns true 
	{
	throw new Exception(response.Error);  
        }

**Comment by brockallen** [comment]
Your client needs to have trust in the SSL cert (or its issuer). If you have a PS account, watch the first video from Dom's "web api" security module. It covers all of this.
