### ISSUE TITLE
Logout - Two or More Tabs - Token Manager

### ISSUE THREAD

**Issue by israelpereira** [IdentityServer/Thinktecture.IdentityServer3.Samples#77]
Hi,

I saw an unexpected behavior using the TokenManager Logout feature.

When I have two browser tabs open and I click to Logout, just the active tab do the Logout.. the other tab for some reason receives the event "Token Obtained" and still able to send the removed token.. I tried to find what is happening, but until now I didn't find nothing.. I just guess that is probably some issue with the delegate window.addEventListener("storage".. within the TokenManager.. 

I still trying to understand what is happening..

Thoughts?

It is easy reproduce with the OAuthJS sample.

**Comment by brockallen** [comment]
Hmm, ok, thanks. I'll look into it.

**Comment by brockallen** [comment]
Ok, I tracked it down. Fixed on dev. Thanks.
