### ISSUE TITLE
CORS configuration error

### ISSUE THREAD

**Issue by MohammadKani** [IdentityServer/Thinktecture.IdentityServer3.Samples#78]
using JavaScript Implicit Client - TokenManager as client and SelfHost (Minimal) as IDP but when test get the following error : 

XMLHttpRequest cannot load https://localhost:44333/core/.well-known/openid-configuration. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:21575' is therefore not allowed access.

**Comment by leastprivilege** [comment]
Check the docs on CORS
