### ISSUE TITLE
Any Suggestions for Creating AccessTokens for Single Page App

### ISSUE THREAD

**Issue by skatukojwala** [IdentityServer/Thinktecture.IdentityServer3.Samples#79]
We have a WebSite which is used to loads our Single Page JavaScript App into the browser.  Currently out WebSite launcher uses Code Flow to get a AccessToken and RefreshToken and these tokens are stored on the server.  

We need to create a new AccessToken (which is short lived) based on above AccessToken (Since the WebSite had the RefreshToken) for the user. 

Any suggested approach for this?. 

I came across an article http://alexbilbie.com/2014/11/oauth-and-javascript/ but this more sounds laborious to me.   

Any suggestions towards creating these delegated AccessTokens?.  Since the Single Page App loads into the browser, we don't want this to hold to RefreshToken but should get AccessToken based on the the AccessToken assigned to the user on the server.

**Comment by brockallen** [comment]
We have an OAuth2 client helper in the IdentityModel project/NuGet. Also, look at the samples to get an idea for what you can do (or what needs to be done).

**Comment by skatukojwala** [comment]
Thank you Allan, I will take a look into it.  This information is very helpful to us. 

Is there anyway of generating Delegated AccessToken using you IdentityServer. The idea is 

The WebApplication which loads the SPA will request for AccessToken and RefreshToken.  
It will again request AccessToken without RefreshToken for SPA using this AccessToken that we got for WebApplication loader.

**Comment by brockallen** [comment]
Yes, look into the custom grant validator extensibility point.

**Comment by skatukojwala** [comment]
Thank you Allan.

**Comment by skatukojwala** [comment]
Is this something from SelfHost.Extensions.CustomGrantValidator() from ..\Thinktecture.IdentityServer3.Samples-master\source\Custom Grants (more customization)

**Comment by brockallen** [comment]
That's the sample.

**Comment by skatukojwala** [comment]
Thank you for Clarifying it.

**Comment by yusbel** [comment]
Do we use custom grants for SPA? - Can we use implicit flow using ADAL.js for SPA?

**Comment by leastprivilege** [comment]
SPAs use implicit flow. ADAL is for MS backends only.

**Comment by yusbel** [comment]
yes, I'm aware that we need to use implicit flow. I was hoping to leverage the ADAL.js to do the client side part. Do we have a sample for spa implicit flow or hybric flow?, I would like to leverage some of the javascript code already tested.

**Comment by brockallen** [comment]
Use this, then: https://www.npmjs.com/package/oidc-client

The source is here: https://github.com/IdentityModel/oidc-client-js/tree/dev

And we have an updated IdSvr sample suing it on dev: https://github.com/IdentityServer/IdentityServer3.Samples/tree/dev/source/Clients/JavaScriptImplicitClient
