### ISSUE TITLE
Side-by-Side authentication

### ISSUE THREAD

**Issue by kavinho** [IdentityServer/Thinktecture.IdentityServer3.Samples#80]
In case I have a WepApi 2 that I want to be protected side-by-side authentication approach (forms Auth,  Identity server 3) how can I do this? either successful authorization will should let access to  WebApi.(I know protecting WebAPi2 with formsAuth is not a good practice, but there are some legacy constraints)

I think this needs be some code on WepApi 2 side, some message handler?

The scenario details: there is  web MVC.NET application which can access the WebApi 2 site, using forms authentication, cors, a trick with Machine key, and cookie names, to make it work.
Now business has decided to expose WebApi 2 to some clients. We thought of OAuth/IdentityServer.
But I cannot figure out where in the WebApi, I can detect the credentials and call FormsAuthorization or TokenbasedAutrhorization (IdentityServer).

**Comment by brockallen** [comment]
So you want to protect your Web API with both cookies and tokens? Tokens are solving the security vulnerability of cookies, and it's simpler to just use one form of authentication (i.e. tokens). I'd not suggest trying to do this.

**Comment by kavinho** [comment]
@brockallen: thanks for your reply. 
Yes, both will be in place and any requests that can satisfy either of these will be able to use the WebApi.

I know tokens are enough to protect, however there are legacy systems(MVC.NET) that are using WebApi already. That's a constraint that needs time to be removed.

for the mean time,  how can a the WebApi , detect and relay the authorization to the matching authorizer(forms OR token)?

**Comment by brockallen** [comment]
I don't know if it's possible, but 2 different APIs might be an option. But if that's not an option, then yes, you'll need 2 different interception components to do your security.
