### ISSUE TITLE
WPF Implicit Client url length

### ISSUE THREAD

**Issue by evilgamr** [IdentityServer/Thinktecture.IdentityServer3.Samples#82]
We are facing a problem with the "WpfClient implicit sample". When the final redirection, that includes the tokens in an "oob://..." uri, exceeds some lenght the webbrowser control refuses to fire the "Navigating" event and thus the process does not complete. The login window shows the error message "Some content or files on this webpage require a program that you don't have installed".

This seems to be a bug in the WPF WebBrowser control, but renders the technique shown in the sample unusable in real world application.
Were you aware of this problem? Do you know how it can be avoided?

Thank you.

**Comment by brockallen** [comment]
Try to use reference tokens for API calls and see if the URL is short enough.

**Comment by leastprivilege** [comment]
The WPF browser control uses IE - IE has a limitatio of 2048 bytes.

https://stackoverflow.com/questions/812925/what-is-the-maximum-possible-length-of-a-query-string

As Brock said - either use reference tokens to keep the size small (or less claims) - or use something like https://github.com/cefsharp/CefSharp (chrome browser control).

**Comment by evilgamr** [comment]
As a temporary workaround we changed the RedirectUrl from oob://localhost/... to http://oob/...
The size limit problem does not appear using this protocol in the url.

I will try the form_post solution and let you know.

**Comment by alex-bogomaz** [comment]
response_mode=form_post works just fine. Just add ```additionalValues: new Dictionary<string,string> { {"response_mode", "form_post"} }``` parameter to the ```OAuth2Client.CreateAuthorizeUrl``` call.

In this case it is not possible to create ```AuthorizeResponse``` object inside ```webView_Navigating```. Instead you should grab form data from the Html document (using dynamics): 
```csharp
  var forms = ((WebBrowser)sender).Document).IHTMLDocument2_forms as IEnumerable;
  var form = forms.OfType<dynamic>().First() as IEnumerable;
  var values = form.OfType<dynamic>().ToDictionary(x => (string) x.name, x => (string) x.value);
```

**Comment by leastprivilege** [comment]
https://github.com/IdentityServer/IdentityServer3.Samples/blob/dev/source%2FClients%2FWpfClient%2FLoginWebView.xaml.cs#L48
