### ISSUE TITLE
Use UserInfo end point without Thinktecture.IdentityModel.Client

### ISSUE THREAD

**Issue by MohammadKani** [IdentityServer/Thinktecture.IdentityServer3.Samples#84]
how can i get userinfo data without add Thinktecture.IdentityModel.Client dependency to my project?

**Comment by leastprivilege** [comment]
with HTTP

http://openid.net/specs/openid-connect-core-1_0.html#UserInfo

**Comment by mschulz531** [comment]
;)

**Comment by MohammadKani** [comment]
thank you Dominick.
