### ISSUE TITLE
Any idea why the model is not getting bound to the Login Page

### ISSUE THREAD

**Issue by skatukojwala** [IdentityServer/Thinktecture.IdentityServer3.Samples#85]
We are seeing issue with Model not getting bound to the HTML Page.  We see the page like this. 

![authcode](https://cloud.githubusercontent.com/assets/8934280/6424371/afc67540-beac-11e4-9142-205463a5c81f.png)

**Comment by leastprivilege** [comment]
RAMMFAR!!!

https://github.com/IdentityServer/Thinktecture.IdentityServer3.Samples/blob/master/source/WebHost%20(minimal)/WebHost/Web.config#L12-L14
