### ISSUE TITLE
Simplest OAuth2's IdSrv does not serve requests

### ISSUE THREAD

**Issue by fabriciomurta** [IdentityServer/Thinktecture.IdentityServer3.Samples#86]
Hello,

I've just set up the simplest sample here, following step by step, and installing NuGet packages. Using VS2013 upd4 here.
I can run the IdSrv just fine. But it does not reply requests...
I can't understand where it is defined that the path must be /connect/token, what defines that? All I get is connection closed responses (from the same example's client).
If I try to connect to the server via telnet, the connection is established successfully (no, no firewall issue), but upon anything I type, I get disconnected. I wonder there's something amiss in the project's configuration or that no longer works on newer VS versions.

I can't seem to get any log messages from the IdSrv program, I failed some attempts to set Owin's Kanata debug mode to max verbosity (so I can watch server requests there).

Well, what I get so far is:
```
IdentityServer.vshost.exe Warning: 0 : [Thinktecture.IdentityServer.Core.Configu
ration.IdentityServerServiceFactory]: 01/03/2015 03:25:29 +00:00 -- Authorizatio
nCodeStore not configured - falling back to InMemory
IdentityServer.vshost.exe Warning: 0 : [Thinktecture.IdentityServer.Core.Configu
ration.IdentityServerServiceFactory]: 01/03/2015 03:25:29 +00:00 -- TokenHandleS
tore not configured - falling back to InMemory
IdentityServer.vshost.exe Warning: 0 : [Thinktecture.IdentityServer.Core.Configu
ration.IdentityServerServiceFactory]: 01/03/2015 03:25:29 +00:00 -- ConsentStore
 not configured - falling back to InMemory
IdentityServer.vshost.exe Warning: 0 : [Thinktecture.IdentityServer.Core.Configu
ration.IdentityServerServiceFactory]: 01/03/2015 03:25:29 +00:00 -- RefreshToken
Store not configured - falling back to InMemory
IdentityServer.vshost.exe Warning: 0 : [Startup]: 01/03/2015 03:25:29 +00:00 --
No signing certificate configured.
server running...
```

So far, expected. Now on VS's output log:
(in addition to messages logged in the app console above).
```
The thread 0x4fd0 has exited with code 259 (0x103).
The thread 0x10d7c has exited with code 259 (0x103).
The thread 0x18eac has exited with code 0 (0x0).
```
These `thread` lines appear slowly thru time regardless of connecting to the host or not. Connecting thru telnet nor using the console client from the same sample gives any answer other than connection being dropped. On telnet, I can type the command line (like GET /) and hit enter. And then the connection is closed.
The response I get on the client is `An existing connection was forcibly closed by the remote host`.

Any light to this?

**Comment by fabriciomurta** [comment]
Is there a reason anywhere for the server to only work with a port number matching the 443NN pattern?

Weird. After setting it to a port in the range 44300-44399, it stopped to just drop connections, and now it's complaining about the certificate. Unexpected, at least to me. At least some progress here.

**Comment by mschulz531** [comment]
I assume you are using IIS Express and localhost...if so, your IIS Express is not configured correctly for SSL.  Google for it and you will find instructions.  IIS Express config files are located in your Documents\IIS Express\Config folder, that should get you started.

**Comment by cabrinoob** [comment]
I have the same issue with the "Simplest OAuth2 Walkthrough" sample. I'am not sure this sample is using IISExpress because the IdSrv is self hosted in a console application.

**Comment by leastprivilege** [comment]
IdSrv is running in a self host - the rest is not.

Visual Studio sets up SSL on the above mentioned port range. If Visual Studio and IIS Express are setup correctly, this should not be an issue.

**Comment by cabrinoob** [comment]
Yes the API is running under IISExpress and it's working good on my computer. It respond but I have a 401 Unothorized which is the expected behavoir.

But the IdSrv, which is running on port 44333, does not seem to respond. 

The GetClientToken() crashes when calling the RequestClientCredentialsAsync method.

    static TokenResponse GetClientToken()
        {
            var client = new OAuth2Client(
                new Uri("https://localhost:44333/connect/token"),
                "silicon",
                "F621F470-9731-4A25-80EF-67A6F7C5F4B8");

            return client.RequestClientCredentialsAsync("api1").Result;
        }

And in the IdSrv console I still have :

    IdSrv.vshost.exe Warning: 0 : [Thinktecture.IdentityServer.Core.Configuration.Id
    entityServerServiceFactory]: 16/03/2015 11:01:09 +00:00 -- AuthorizationCodeStor
    e not configured - falling back to InMemory
    IdSrv.vshost.exe Warning: 0 : [Thinktecture.IdentityServer.Core.Configuration.Id
    entityServerServiceFactory]: 16/03/2015 11:01:09 +00:00 -- TokenHandleStore not
    configured - falling back to InMemory
    IdSrv.vshost.exe Warning: 0 : [Thinktecture.IdentityServer.Core.Configuration.Id
    entityServerServiceFactory]: 16/03/2015 11:01:09 +00:00 -- ConsentStore not conf
    igured - falling back to InMemory
    IdSrv.vshost.exe Warning: 0 : [Thinktecture.IdentityServer.Core.Configuration.Id
    entityServerServiceFactory]: 16/03/2015 11:01:09 +00:00 -- RefreshTokenStore not
    configured - falling back to InMemory
    IdSrv.vshost.exe Warning: 0 : [Startup]: 16/03/2015 11:01:09 +00:00 -- No signin
    g certificate configured.
    server running...


@fabriciomurta : Did you find a solution to this problem??

Thank you

**Comment by leastprivilege** [comment]
Feel free to move IdSrv to any other port (or IIS Express) or try using plain HTTP first (set the RequireSsl to false on the options).

**Comment by cabrinoob** [comment]
ok, so I remove the SSL (RequireSsl = false) and it's working perfectly. I'll continue without ssl with next samples.

Thank you for your help Dominick

**Comment by fabriciomurta** [comment]
The pull request on IdentityServer/IdentityServer.Samples#87 was the way I found to overcome the issue.

Basically I set up SSL to accept invalid certificates no matter what on the test projects. Something @leastprivilege deeply condemned, and ultimately refused the pull request. =]

**Comment by leastprivilege** [comment]
true. Learn to SSL :p

**Comment by florinc** [comment]
I've just ran into the same issue. Yes, the cause was that the IIS Express was not configured for SSL. Easy fix: Properties (F4) on `Apis` proj and switch `SSL Enabled` to `true`.

**Comment by longpshorn** [comment]
I may be missing something, but, the solutions so far are either to turn off SSL or move from OWIN to IISExpress in order to get SSL set up. I assume there is a way to get SSL working with a self-hosted OWIN instance, right? I have googled a fair amount but can't find any info on getting this set up. Does anyone have any pointers to a tutorial to do this?

**Comment by fabriciomurta** [comment]
Well, the pull request allows you to use self-hosted owin instance, effectively disabling certificate verification (SOMEWHAT like adding a self-signed certificate and adding its CA to the local trusted certs list)

**Comment by longpshorn** [comment]
First off, thank you for your response.

Am I correct in interpreting your statement as that when self-hosting an OWIN instance, you can't use a self-signed certificate without disabling the cert verification? Said another way, when using OWIN self-hosting, one MUST have CA-signed cert?

If that is correct, I guess I can accept that. I feel like there should be a better solution though.

**Comment by leastprivilege** [comment]
No - you can use any SSL certificate for self hosting. But it must be trusted in the SSL sense from a client point of view.

I had no specific reason to use a self host for this sample (besides just showing a different approach opposed to most other samples).

If Visual Studio is setup correctly - it does pre-configure the 44300 above address range with listening permissions and a localhost cert.

You can move to IIS Express if self hosting does not work for you or investigate how to manually configure HTTP.SYS (e.g. using netsh).

**Comment by AKATSUKY** [comment]
@leastprivilege  you really should add this VS configuration to the documentation. That will improve your work even more.
Great work anyway.

**Comment by bcreech** [comment]
Really, Really handwavey stuff here. 

That the 'simplest' walkthrough does not work out of the box is very telling.

**Comment by fabriciomurta** [comment]
I agree that the simplest walkthrough should be made simpler -- as meant to run in a local, testing environment, free of any SSL-whatsoever attacks and focusing the main feature of the project.

But I can't simply agree it is all garbage. Just could use a little trimming =]

**Comment by bcreech** [comment]
Look, if the people who wrote the product cant provide a working example then ... yea... I tend to want to flee. 

Also, think about it. If the 'simplest'  thing dosent work can you imagine dealing with this in production? 

I will leave it to you all. good luck. 

Im moving on. Its not me- its them .

**Comment by leastprivilege** [comment]
You all know the concepts of PRs - this is not a product - it's an OSS project.

If you think you can add value to it (fix a bug, simplify the code, add instructions) - please do.

Sorry @bcreech - comments like this remind me of https://twitter.com/eranhammer/status/679163371707568129

**Comment by fabriciomurta** [comment]
actually, [there was one](https://github.com/IdentityServer/IdentityServer3.Samples/pull/87). :P

no hard feelings (from my side, at least)

**Comment by brockallen** [comment]
The problem with that PR was it's not the right approach.

**Comment by cabrinoob** [comment]
what does "PR" stand for?

**Comment by bcreech** [comment]
@leastprivilege, so your 'how this works' code, well... doesn't and all you can do is make smartass comments?

Perhaps this line of work isnt for you?
