### ISSUE TITLE
GetExternalLoginInfo return null

### ISSUE THREAD

**Issue by sadeghhp** [IdentityServer/Thinktecture.IdentityServer3.Samples#89]
Hi, 
I'm using default asp.net mvc application template with asp.net identity 2 and with openidconnect.  I'm trying to connect to my identityserver3 and everything is ok until ExternalLoginCallback method in account controller called.
by using google middleware  AuthenticationManager.GetExternalLoginInfoAsync() returns a correct logininfo object but in oppenidconnect and identityserver3 , this method returns null ! what is the problem ?

**Comment by leastprivilege** [comment]
First of all - why are you using that code. All you need the OIDC MW (and maybe some claims transformation).

Microsoft's template code assumes Microsoft's claim types. We use the standard claim types for OIDC - that's why their sample code fails.

**Comment by leastprivilege** [comment]
Core would be also better suited for these kind of questions - since this is not an issue with one of our samples - is it?
