### ISSUE TITLE
Use window.location.replace(url) instead of window.location = url to prevent history back in oidc.js

### ISSUE THREAD

**Issue by devlz303** [IdentityServer/Thinktecture.IdentityServer3.Samples#90]
I am using the oidc.js code and think the redirectForToken and redirectForLogout functions can be improved by changing the window.location = url calls into window.location.replace(url).

This way the url will not be saved in session history, meaning the user won't be able to use the Back button to navigate to it.

**Comment by brockallen** [comment]
But the user might want to go back, no?

**Comment by devlz303** [comment]
I think you're right. But I don't think you want to go back to the callback page (because the only purpose of the callback page is retrieving the token from the hash and redirecting to index page.

In my own callback page I have changed the script to do a location.replace so when the user uses the back button they don't end up at the callback page. I also changed the code in the oidc.js, but maybe that's not correct (or needed).

**Comment by brockallen** [comment]
Ah yes -- I buy that. Done on dev. Thanks for the hint.
