### ISSUE TITLE
Impossible to open Constants.csproj file

### ISSUE THREAD

**Issue by pomeh** [IdentityServer/Thinktecture.IdentityServer3.Samples#91]
When I open the `Clients.sln` solution, the project `Constants` cannot be loaded, there no error message but "Impossible to load this project".

After a bit of headache and fighting against my Visual Studio, I've figured that the line below causes the problem:

```
<ProjectTypeGuids>{786C830F-07A1-408B-BD7F-6EE04809D6DB};{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}</ProjectTypeGuids>
```

When I remove this line, the project can be loaded fine and everything can compile.

For your information, I'm using Microsoft Visual Studio Ultimate 2013 (Version 12.0.21005.1 REL) and Microsoft .NET Framework (Version 4.5.50938), on Windows 7 Enterprise with SP1. I didn't install any complementary SDK on my own, so I might not have one. I have used the latest version available on the master today (so basically it means this commit https://github.com/IdentityServer/Thinktecture.IdentityServer3.Samples/commit/96db83a87ebfe3b129f697aae02fb7ab3295317c).

Maybe you know where this problem come from, and maybe it'll help anyone facing the same situation.

Cheers,

Romain

**Comment by leastprivilege** [comment]
It is a portable library. That's all.

**Comment by pomeh** [comment]
Ok, so my problem is really weird. There's nothing you can do about it so the close seems fair :)
