### ISSUE TITLE
JavaScript Clients: post_logout_redirect_uri not encoded in redirectForLogout

### ISSUE THREAD

**Issue by Nicholi** [IdentityServer/Thinktecture.IdentityServer3.Samples#92]
In oidc.js the usage of settings.post_logout_redirect_uri is just appended to the uri string as is. I suppose depending on the browser and also on the actual uri the browser MIGHT correctly encode it for you, but otherwise it won't work in all instances.

```
            url += "?post_logout_redirect_uri=" + encodeURIComponent(settings.post_logout_redirect_uri);
            url += "&id_token_hint=" + encodeURIComponent(id_token_hint);
```

Looks like just an oversight, as encodeURIComponent is used all throughout createTokenRequestAsync.

**Comment by brockallen** [comment]
Done -- thanks for the heads up.
