### ISSUE TITLE
We cannot pass any custom errors information in AuthenticateResult

### ISSUE THREAD

**Issue by skatukojwala** [IdentityServer/Thinktecture.IdentityServer3.Samples#93]
We are overriding following method to customize our user logins, We need to pass lot of error information if the login fails, Since the is returned as part of generic type we cannot extend AuthenticateResult to pass failure information.  

Please let me know if there is any other better way of handling these errors.  Since we are customizing our login screens and errors messages we need more information to be passed around.   

public Task<AuthenticateResult> AuthenticateLocalAsync(string username, string password, SignInMessage message)
{

}

**Comment by leastprivilege** [comment]
wrong repo.
