### ISSUE TITLE
Owin Security in IdSrv

### ISSUE THREAD

**Issue by stevenfirstrowinc** [IdentityServer/Thinktecture.IdentityServer3.Samples#96]
Looking at the example CustomUserService project I see that we are able to access the Owin IAuthenticationManager using the following

            // this verifies that we have a prtial signin from idsvr
            var ctx = Request.GetOwinContext();
            var authentication = await ctx.Authentication.AuthenticateAsync(Constants.PartialSignInAuthenticationType);

When I use this same approach in my IdSrv I get a null returned from teh AuthenticateAsync method.  When I look in the Owin environment dictionary I am missing several of the IdSrv keys that I get in the sample.  I don't see any particular line of code that is making the sample work and mine not.  Can you point it out to me?

**Comment by brockallen** [comment]
Your code must be under same path as idsvr 's mapped path, otherwise its code won't run. 

-Brock

**Comment by stevenfirstrowinc** [comment]
do you mean that when I map IdSrv to
            app.Map("/identity", idsrvApp =>
    ....

My controller must have 
        [Route("identity/eula")]

as well?

**Comment by stevenfirstrowinc** [comment]
nevermind that did it.  Thank you very much
